app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
 ]

newblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
urlpatterns = [
       # post views
    #url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'), url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
           r'(?P<post>[-\w]+)/$',
           views.post_detail,
           name='post_detail'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$',views.post_detail,name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share,name='post_share'),
]

similarface/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls',namespace="polls")),
    url(r'^blog/', include('blog.urls',namespace="blog")),
    url(r'^newblog/', include('newblog.urls',namespace="newblog",app_name='newblog')),
    url(r'^app/', include('app.urls',namespace="app")),
]

newblog/models.py
#coding:utf-8
from django.db import models

# Create your models here.

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    def get_absolute_url(self):
        return reverse('newblog:post_detail',
                          args=[self.publish.year,
                                self.publish.strftime('%m'),
                                self.publish.strftime('%d'),
                                self.slug])
    STATUS_CHOICES = (
       ('draft', 'Draft'),
       ('published', 'Published'),
   )
    #
    title = models.CharField(max_length=250)
    #
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    #
    author = models.ForeignKey(User,related_name='blog_posts')
    #
    body = models.TextField()
    #
    publish = models.DateTimeField(default=timezone.now)
    #
    created = models.DateTimeField(auto_now_add=True)
    #
    updated = models.DateTimeField(auto_now=True)
    #
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    objects = models.Manager() # The default manager.

    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title




class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments')
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

newblog/forms.py
# coding:utf-8
__author__ = 'similarface'
from django import forms

class EmailPostForm(forms.Form):
    '''
    email的form标签体
    '''
    #
    name = forms.CharField(max_length=25)
    #发件人
    email=forms.EmailField()
    #收件人
    to=forms.EmailField()
    #消息内容
    comments=forms.CharField(required=False,widget=forms.Textarea)



from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name', 'email', 'body')

newblog/views.py
# coding:utf-8
from django.shortcuts import render
from django.core.mail import send_mail
# Create your views here.
from .forms import EmailPostForm
from django.shortcuts import render, get_object_or_404

from .models import PublishedManager, Post

from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from .models import Comment
from .forms import CommentForm
from django.views.generic import ListView

class PostListView(ListView):
    '''
    代替下面的post_list方法
    '''
    #查询结果集
    queryset = Post.published.all()
    #填充的容器名称
    context_object_name = 'posts'
    #分页的大小
    paginate_by = 3
    #填充的模版
    template_name = 'newblog/post/list.html'


def post_list(request):
    '''
    分页代码
    :param request:
    :return:
    '''
    object_list = Post.published.all()
    #分页 3个一页
    paginator=Paginator(object_list,3)
    #获取页号
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request, 'newblog/post/list.html', {'page': page,'posts': posts})


def post_detail(request, year, month, day, post):
    #post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    post = get_object_or_404(Post, slug=post,status='published',publish__year=year)

    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #创建commetn对象但是不妨如数据库
            new_comment = comment_form.save(commit=False)
            #分配当前的post给comment
            new_comment.post = post
            #保存到数据库
            new_comment.save()
        else:
            comment_form = CommentForm()
        return render(request,'newblog/post/detail.html',{'post': post,'comments': comments, 'comment_form': comment_form})



    return render(request,'newblog/post/detail.html',{'post': post})

def post_share(request,post_id):
    post=get_object_or_404(Post,id=post_id,status='Published')
    sent=False
    if request.method=='POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com',[cd['to']])
            sent = True
    else:
        form=EmailPostForm()
    return render(request,'newblog/post/share.html',{'post':post,'form':form})

newblog/templates/newblog/post/detail.html
{% extends "newblog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url "newblog:post_share" post.id %}">
            Share this post
        </a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

newblog/templates/newblog/post/list.html
{% extends "newblog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    <!-- 分页代码写在这儿的 这儿是page_obj -->
    {% include "newblog/pagination.html" with page=page_obj %}
{% endblock %}

newblog/templates/newblog/post/share.html
{% extends "newblog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}